# New prefix
# unbind C-b
# set -g prefix 'C-\'
# bind-key 'C-\' send-prefix

# split horizontally right: '=' is '+': put a | divission
bind '=' split-window -h
bind '\' split-window -h
# unbind %

bind - split-window -v
# unbind '"'

bind J split-window -v
bind K split-window -v -d
bind H split-window -h -d
bind L split-window -h

# reload
bind r source-file ~/.tmux.conf

# navigation
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R

# replace: default 'l'
bind _ select-window -l
# replace: default 'L'
bind + switch-client -l


# enable mouse
set -g mouse on

# 
set -g base-index 1

# layout
set -g default-terminal "tmux-256color"
# for i in {0..255}; do printf "\x1b[38;5;${i}mcolor${i} - ██████████\n"; done


#et -g status-bg teal
#et -g status-fg white
set -g status-bg color27
set -g status-fg color15
set -g window-status-style bg=teal
#et -g window-status-current-style bg=red,fg=white
#et -g window-status-current-style bg=yellow,fg=black
#et -g window-status-current-style bg=blue,fg=black
set -g window-status-current-style bg=color11,fg=black

#et -g status-right "|S:#S|W:#I|P:#P,#D|#h"
set -g status-right "|W:#I|P:#P,#D"
set -g status-left "[S:#S] "

# Windows titles: Session|Window
#   (ie, the name in tab of the terminal app)
set-option -g set-titles on
set-option -g set-titles-string "tmux:[#S][#I]"
# don't rename windows automatically
#et-option -g allow-rename off



