#!/bin/bash
# vim: ft=sh:

###
### mvf
### Python

# Disable __pycache__ dirs
# https://docs.python-guide.org/writing/gotchas/#disabling-bytecode-pyc-files
export PYTHONDONTWRITEBYTECODE=1

###
### Pip
###
# Tip: pip completion
# pip completion --bash > ~/bash_completion.d/pip.bash-completion


###
### venv
###
# virtualenv: disable '(venv)' prefix in PS1
export VIRTUAL_ENV_DISABLE_PROMPT=1

#
# Black       0;30     Dark Gray     1;30
# Red         0;31     Light Red     1;31
# Green       0;32     Light Green   1;32
# Brown       0;33     Yellow        1;33
# Blue        0;34     Light Blue    1;34
# Purple      0;35     Light Purple  1;35
# Cyan        0;36     Light Cyan    1;36
# Light Gray  0;37     White         1;37

     red='\e[01;31m'
   green='\e[01;32m'
  yellow='\e[01;33m'
   brown='\e[00;33m'
    blue='\e[01;34m'
 magenta='\e[01;35m'
    cyan='\e[01;36m'
   white='\e[01;37m'
    gray='\e[00;37m'
   reset='\e[0m'

function __venv_ps1() {
  if [ "${VIRTUAL_ENV}" ]
  then
#   msg = "${green}[${yellow}🐍 ${VIRTUAL_ENV##*/}${green}]"
#   echo -n '🐍 '
    echo -n "[${VIRTUAL_ENV##*/}]🐍"
  fi
}


###
### Pyenv
###   https://github.com/pyenv/pyenv
###
# export PYENV_ROOT=~/.pyenv
if which pyenv 2>/dev/null 1>/dev/null
then eval "$(pyenv init -)"
fi


###
### pipenv
###
# pipenv: Pipfile.lock
export PIPENV_CUSTOM_VENV_NAME=venv
export PIPENV_VENV_IN_PROJECT=1
export PIPENV_VERBOSITY=-1
export PIPENV_DEFAULT_PYTHON_VERSION=3

eval "$(_PIPENV_COMPLETE=bash_source pipenv)"

##
## Generated by
##   _PIPENV_COMPLETE=bash_source pipenv
##
_pipenv_completion() {
    local IFS=$'\n'
    local response

    response=$(env COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD=$COMP_CWORD _PIPENV_COMPLETE=bash_complete $1)

    for completion in $response; do
        IFS=',' read type value <<< "$completion"

        if [[ $type == 'dir' ]]; then
            COMPREPLY=()
            compopt -o dirnames
        elif [[ $type == 'file' ]]; then
            COMPREPLY=()
            compopt -o default
        elif [[ $type == 'plain' ]]; then
            COMPREPLY+=($value)
        fi
    done

    return 0
}

_pipenv_completion_setup() {
    complete -o nosort -F _pipenv_completion pipenv
}

_pipenv_completion_setup;

