#!/usr/bin/env bash
#
# |FILENAME|
#     |CURSOR| [Description here]
#     .
#
#     |AUTHOR|           |EMAIL|
#     |DATE|
#

PATH=/opt/csw/bin:opt/csw/sbin
PATH=$PATH:/opt/local/bin:/opt/local/sbin
PATH=$PATH:/usr/local/bin:/usr/local/sbin
PATH=$PATH:/usr/bin:/usr/sbin:/bin:/sbin

[ "$1" != '-f' ] && {
    echo
    echo "Usage: ${0##/*/} -f "
    echo
    echo
    exit 2
}


