
FROM almalinux

# common stuff
RUN dnf install -y bash util-linux which

# this container
RUN dnf install -y sudo shadow-utils git

RUN groupadd -g 1001    dev
RUN useradd  -u 1001 -g dev -s /bin/bash -d /home/dev dev
RUN echo dev | passwd --stdin dev

WORKDIR /work/mv-home

CMD [ "/bin/bash" ]
